### ISSUE TITLE
Back Stack maintain Without Recreating Fragment

### ISSUE THREAD

**Issue by anubhav217** [st235/ExpandableBottomBar#75] opened 2021-09-15 19:11 UTC

**Comment by st235** [comment] 2021-09-21 07:56
Hello 👋

Thank you very much for using this library. 
This issue is a duplicate of https://github.com/st235/ExpandableBottomBar/issues/74. Let's continue discussion there.

Best wishes,
Alex

**Closed** 2021-09-21 07:56 UTC
Labels: duplicate
