### ISSUE TITLE
Class referenced in the layout file, github.com.st235.lib_expandablebottombar.ExpandableBottomBar, was not found in the project or the libraries

### ISSUE THREAD

**Issue by shahzad1** [st235/ExpandableBottomBar#90] opened 2022-08-26 10:38 UTC
Am I doing wrong here?
Gradle
`implementation 'com.github.st235:expandablebottombar:1.5.1'`
xml
`    <github.com.st235.lib_expandablebottombar.ExpandableBottomBar
        android:id="@+id/expandable_bottom_bar"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="20dp"
        app:exb_backgroundCornerRadius="25dp"
        app:exb_backgroundColor="#2e2e2e"
        app:exb_itemInactiveColor="#fff"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />
`

**Comment by st235** [comment] 2022-08-26 19:24
Hello @shahzad1 👋

Thank you for using the library and reaching out!
Actually, the code looks fine.

Remember to add `mavenCentral` to your gradle file

```
allprojects {
    repositories {
        // your repositories

        mavenCentral()
    }
}
```

You can use [this file](https://github.com/st235/ExpandableBottomBar/blob/master/app/src/main/res/layout/activity_xml_declared.xml#L24) as a reference.

Please, do let me know, if the issue resolved for you otherwise I need more input, like, stack trace, exception, or description of what is going wrong.

**Comment by shahzad1** [comment] 2022-08-27 02:23
`  mavenCentral()`
 Already added

**Comment by st235** [comment] 2022-08-27 08:22
Can you, please, share a link to the project for me to check? If you can't share the exact project here at Github can you, please, prepare a demo project to reproduce the issue?

**Comment by shahzad1** [comment] 2022-08-29 08:59
Its just a Webview App.

**Comment by st235** [comment] 2022-09-10 12:36
@shahzad1,

As I can't reproduce the issue and have not heard from you I decided to close the issue. Hopefully, the issue is resolved for you.
However, If you need any further help or assistance - just create a new issue and explain the problem there. 

Thank you for using the library and happy coding!

**Closed by st235** 2022-09-10 12:36 UTC
Labels: help wanted
